Prevent gridware command error if no args given
Previously, when run without arguments the `alces gridware` command
would give the following error due to the `ARGV` array being empty:

```
[alces@login1(bobcluster) ~]$ alces gridware
/opt/clusterware/libexec/actions/gridware:46:in `<main>': undefined method `length' for nil:NilClass (NoMethodError)
```

Checking that `ARGV` is not empty before accessing it prevents this, and
makes Gridware itself handle the error by stating this is an `invalid
command`.